[09/14/22 19:01:04] [34mINFO    [39m Loaded cache labels: [1m448[22m found, [1m0[22m missing, [1m1[22m empty, [1m0[22m corrupt.                                                                ]8;id=790617;file:///home/arkar/ME/Vision-Kit/vision_kit/data/datasets/yolo.py\yolo.py]8;;\:]8;id=917804;file:///home/arkar/ME/Vision-Kit/vision_kit/data/datasets/yolo.py#58\58]8;;\
                    [34mINFO    [39m Loaded cache labels: [1m127[22m found, [1m0[22m missing, [1m0[22m empty, [1m0[22m corrupt.                                                                ]8;id=631646;file:///home/arkar/ME/Vision-Kit/vision_kit/data/datasets/yolo.py\yolo.py]8;;\:]8;id=353675;file:///home/arkar/ME/Vision-Kit/vision_kit/data/datasets/yolo.py#58\58]8;;\
                    [34mINFO    [39m Loaded cache labels: [1m63[22m found, [1m0[22m missing, [1m0[22m empty, [1m0[22m corrupt.                                                                 ]8;id=735082;file:///home/arkar/ME/Vision-Kit/vision_kit/data/datasets/yolo.py\yolo.py]8;;\:]8;id=740251;file:///home/arkar/ME/Vision-Kit/vision_kit/data/datasets/yolo.py#58\58]8;;\
[09/14/22 19:01:06] [34mINFO    [39m Loaded average state from checkpoint.                                                                                     ]8;id=931514;file:///home/arkar/ME/Vision-Kit/vision_kit/core/train/trainer.py\trainer.py]8;;\:]8;id=761296;file:///home/arkar/ME/Vision-Kit/vision_kit/core/train/trainer.py#211\211]8;;\
Using 16bit native Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
[38mValidation[39m [38m━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━[39m [38m4/8[39m [38m0:00:01 • 0:00:01[39m [38m4.72it/s
Traceback (most recent call last):
  File "/home/arkar/ME/Vision-Kit/scripts/eval.py", line 57, in <module>
    trainer.validate(model_module, datamodule.val_dataloader())
  File "/home/arkar/virtualenvs/github_env/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 774, in validate
    return self._call_and_handle_interrupt(self._validate_impl, model, dataloaders, ckpt_path, verbose, datamodule)
  File "/home/arkar/virtualenvs/github_env/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/arkar/virtualenvs/github_env/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 821, in _validate_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/arkar/virtualenvs/github_env/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
    results = self._run_stage()
  File "/home/arkar/virtualenvs/github_env/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1249, in _run_stage
    return self._run_evaluate()
  File "/home/arkar/virtualenvs/github_env/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1295, in _run_evaluate
    eval_loop_results = self._evaluation_loop.run()
  File "/home/arkar/virtualenvs/github_env/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 207, in run
    output = self.on_run_end()
  File "/home/arkar/virtualenvs/github_env/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 183, in on_run_end
    self._evaluation_epoch_end(self._outputs)
  File "/home/arkar/virtualenvs/github_env/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 293, in _evaluation_epoch_end
    self.trainer._call_lightning_module_hook(hook_name, output_or_outputs)
  File "/home/arkar/virtualenvs/github_env/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1550, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/arkar/ME/Vision-Kit/vision_kit/core/train/trainer.py", line 117, in validation_epoch_end
    map50, map95 = self.evaluator.evaluate_predictions()
  File "/home/arkar/ME/Vision-Kit/vision_kit/core/eval/yolo_eval.py", line 189, in evaluate_predictions
    str(self.seen, num_targets[c]),
[38mValidation[39m [38m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[39m [38m8/8[39m [38m0:00:01 • 0:00:00[39m [38m4.83it/s
[?25h