[09/14/22 18:56:13] [34mINFO    [39m Loaded cache labels: [1m448[22m found, [1m0[22m missing, [1m1[22m empty, [1m0[22m corrupt.                                                                ]8;id=698795;file:///home/arkar/ME/Vision-Kit/vision_kit/data/datasets/yolo.py\yolo.py]8;;\:]8;id=184308;file:///home/arkar/ME/Vision-Kit/vision_kit/data/datasets/yolo.py#58\58]8;;\
                    [34mINFO    [39m Loaded cache labels: [1m127[22m found, [1m0[22m missing, [1m0[22m empty, [1m0[22m corrupt.                                                                ]8;id=600825;file:///home/arkar/ME/Vision-Kit/vision_kit/data/datasets/yolo.py\yolo.py]8;;\:]8;id=139370;file:///home/arkar/ME/Vision-Kit/vision_kit/data/datasets/yolo.py#58\58]8;;\
                    [34mINFO    [39m Loaded cache labels: [1m63[22m found, [1m0[22m missing, [1m0[22m empty, [1m0[22m corrupt.                                                                 ]8;id=911886;file:///home/arkar/ME/Vision-Kit/vision_kit/data/datasets/yolo.py\yolo.py]8;;\:]8;id=85328;file:///home/arkar/ME/Vision-Kit/vision_kit/data/datasets/yolo.py#58\58]8;;\
Traceback (most recent call last):
  File "/home/arkar/ME/Vision-Kit/scripts/eval.py", line 40, in <module>
    model_module = TrainingModule.load_from_checkpoint(
  File "/home/arkar/virtualenvs/github_env/lib/python3.10/site-packages/pytorch_lightning/core/saving.py", line 137, in load_from_checkpoint
    return _load_from_checkpoint(
  File "/home/arkar/virtualenvs/github_env/lib/python3.10/site-packages/pytorch_lightning/core/saving.py", line 205, in _load_from_checkpoint
    return _load_state(cls, checkpoint, strict=strict, **kwargs)
  File "/home/arkar/virtualenvs/github_env/lib/python3.10/site-packages/pytorch_lightning/core/saving.py", line 253, in _load_state
    obj.on_load_checkpoint(checkpoint)
  File "/home/arkar/ME/Vision-Kit/vision_kit/core/train/trainer.py", line 203, in on_load_checkpoint
    if self.ema_model:
  File "/home/arkar/virtualenvs/github_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'TrainingModule' object has no attribute 'ema_model'